### ISSUE TITLE
introspect mapping before using it

### ISSUE THREAD

**Issue by geemang2000** [dobrynya/nomin#10]
Thanks for creating such a cool framework. 

We have a question about retrieving information about the mapping before using it. 
Here is some context:
1) We're using mappers to map from a DB to a domain object
2) The mapper defines the DB fields that we'd like to extract from a ResultSet

Issue:   We'd like to ask the mapper what it's going to map and use this in the select statement (prior to invoking the mapper). We'd like to avoid doing a select * on the DB table.

Is this possible?  We have a chicken and egg issue. 

Or is it possible to give the mapper some metadata / property we could retrieve before invoking the map.

**Comment by dobrynya** [comment]
Hi

Sorry for the late answer, I have recalled about an email right now :)

You are able to define a mapping from ResultSet to YourDomainObject as a
usual mapping:

mappingFor a: Person, b: ResultSet
a.name = { b.getString("name") }
a.lastName = { b.getString("lastName")

It works as expected during mapping result set to an entity.
ResultSet.next() should be controlled by an application.
Mapper should not dictate what you should load from DB. It is
responsibility of your application.

Hope it was useful.

Best regards,
Dmitry


2015-07-01 20:28 GMT+03:00 geemang2000 <notifications@github.com>:
