### ISSUE TITLE
SpringContext usage in mappings

### ISSUE THREAD

**Issue by phi1ipp** [dobrynya/nomin#12]
Hello Dmitry,

Great framework you made, kudos!

Would you mind giving some examples of using SpringContext in a mapping file? Is it just using a bean name?

mappingFor a: Class1, b: Class2
a.f1 = { b.f2 + ' ' + beanName.prop1 }

Thank you!

**Comment by dobrynya** [comment]
Hi Gregory

You are absolutely right! You can use any bean defined in a spring context
in a closure/expression by specifying its bean id. Be accurate to provide
nomin with the spring context instance.

Best regards,
Dmitry
23 Июл 2015 г. 19:51 пользователь "Philipp Grigoryev" <
notifications@github.com> написал:

**Comment by phi1ipp** [comment]
Thank you, worked like charm!

Спасибо :)
