### ISSUE TITLE
Question on nomin mapping

### ISSUE THREAD

**Issue by nishantoo7** [dobrynya/nomin#13]
Hi Group, we are new to nomin mapping. we are planning to use nomin to map entities to JAXB vice-versa. please find the list of issues which we are facing. please let us know if you have any solution for these issues. thanks in advance.
1. Back Referencing issue:- party entity is refrence to address and address has refernce to party back. how we are going to map these things in groovy file. 
2. Type casting : ex:- A has reference B. c extendeds B. when we want to access c attributes using b reference. how to typecast b to c.

**Comment by dobrynya** [comment]
Hi

1. Back referencing can be implemented using callbacks (hooks) as follows
afterAtoB { // or afterBtoA
  a.children.*parent = a
}
Please take an experiment on your data model.

2. If I understand correctly you can use hints as follows
a.reference_To_B_OfC_Class = b.other_side
hint a: CClass

Hope this is useful.

**Comment by nishantoo7** [comment]
Thanks for the answer.
