### ISSUE TITLE
Hierarchical mapping issue

### ISSUE THREAD

**Issue by phi1ipp** [dobrynya/nomin#16]
Hi,

I'd like to indicate an interesting issue I bumped into while working with Nomin. I used it with spring-boot-devtools and discovered that Nomin doesn't work as expected.

One of the issues was, for example, an attempt to convert from Class1 which extends Class. Despite the fact that I have mapping for Class1 -> other Class, Nomin would report that suitable mapping wouldn't exist and would create an automapping, which didn't work for me.

It switched back to normal behavior as soon as I commented out spring-devtool library from the project.

Just wanted to let you know. Maybe it's expected or known thing.

Thank you for the great library!

**Comment by dobrynya** [comment]
Hi Philipp

I suspect spring-boot-devtools do autoproxying your classes. So it can lead to missing defined mappings. In such a case Nomin tries to create a mapping for Class1 -> OtherClass on its own.
Actually I didn't intend to use Nomin to work with proxied classes and didn't test it in that conditions. If you kindly provide me with a unit test reproducing your situation I would do some investigation.

Best regards, 
Dmitry

**Comment by phi1ipp** [comment]
Well, I guess it's not only spring-dev-tools which causes the effect. I excluded it from dependencies, and now I ran into even more weird issue.

So I have two different mappings one of them works fine, but other says that Nomin can't find applicable mappings. Both conversions happen within the same class, just different methods. The problem is that when I do just a simple unit test, both mappings work, but in a integration test one of them fails.

Some methods in the class utilizing Mapper are Transactional, but the working mapping is used both in transactional and non-transactional methods. Non-working mapper is used in non-transactional method. Honestly don't know where to start from. 

Any thoughts are appreciated,
Philipp

**Comment by phi1ipp** [comment]
Well, I ran into the same thing again, and now I kinda found a source of my troubles.

I have EnableTransactionManagement in my configuration. Whenever in a mapping I try to use a bean it causes the same issue.

Here is one of my mappings

import org.nomin.entity.*
import com.icsynergy.scim.domain.Institution
import com.okta.scim.util.model.Membership
import com.okta.scim.util.model.SCIMGroup

mappingFor a: Institution, b: SCIMGroup
b.displayName = a.displayName
b.id = a.name

afterAtoB {
    b.members = integrationService.uiRepo.getInstitutionMembers(a.name).collect {
        def fname = it[1], lname = it[2]
        new Membership(String.valueOf(it[0]), "$lname, $fname")
    }
}

If only i delete `afterAtoB` section or comment out EnableTransactionManagement in my config, Mapper works fine.

Do you have an idea if it can be fixed on my side somehow?

TIA, Philipp

**Comment by dobrynya** [comment]
Philipp, 
as I wrote earlier could you please 
1. create new project (maven/gradle)
2. reproduce your infrastructure (spring-boot etc)
3. create 2 business entities (from & to)
4. create a unit test with expectations that throws unexpected exception.
Then I can debug the problem and eventually find a workaround or do bug fix.

**Comment by phi1ipp** [comment]
Dmitry,

Sorry for the delay. Here is a repo with a test project https://github.com/phi1ipp/nomin-test

Don't push me too hard if i made silly mistakes, i'm still a novice in spring. Please let me know if you need any additional information to troubleshoot.

TIA, Philipp

**Comment by dobrynya** [comment]
No problem. I'll see at the project today or tomorrow. Thanks Philipp

**Comment by dobrynya** [comment]
Actually Spring context was passed to Nomin and interpreted as a mapping case identifier. Spring context should be wrapped with org.nomin.context.SpringContext instead.
