### ISSUE TITLE
Nomin produces memory leaks in SpringContext.

### ISSUE THREAD

**Issue by amelnikoff** [dobrynya/nomin#17]
I have an web application which is using a Nomin with SpringContext, it initialises mapper like this:

`@Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    BeanFactory parentBeanFactory = applicationContext.getAutowireCapableBeanFactory();
    SpringContext springContext = new SpringContext(parentBeanFactory);
    mapper = mapper.context(springContext);
  }`

And I have a problem when the context is destroying, servlet container telling me that it has a memory leaks with thread locals of key org.nomin.core.ContextManager:

[memoryleak.log.txt](https://github.com/dobrynya/nomin/files/229453/memoryleak.log.txt)

My question is how to correctly destroy mapper? I cannot find any method for it in org.nomin.NominMapper interface.

**Comment by dobrynya** [comment]
Hi Alex

First of all, I'd like to thank you for using Nomin.

I've checked your Tomcat log. Currently there is no way to clean
ThreadLocals to prevent memory leak warning becase Nomin cannot know about
every thread running the code. Moreover if I can find the way to clean
ThreadLocal implementing such a decision would cause a performance issue.

Tomcat promises to recreate a new thread over time, so there should not be
a leak.

Best regards,
Dmitry

2016-04-21 11:04 GMT+03:00 Alexey Melnikov <notifications@github.com>:

**Comment by amelnikoff** [comment]
Maybe SpringContext should know about ApplicationContext?
So knowing that ContextManager can monitor for ApplicationContext statuses, and when context is reloaded or stopped, it can free those ThreadLocals.

**Comment by dobrynya** [comment]
Unfortunately, no.
Nomin.context(null) can can make an instance to be unaware of a spring
context instance. But there are empty array lists bounded to some threads
through thread locals. You can see tomcat warnings about them.
At the moment no way to clean these ThreadLocal instances. Of cause Nomin
should provide such oppotunity. In the future I will do the needed.

2016-04-21 17:09 GMT+03:00 Alexey Melnikov <notifications@github.com>:

**Comment by yerdn** [comment]
Hi Dmitry,

Thanks for such great framework! 

I'm exploring possibility to use it in my project as it seems to tick all boxes but this open bug is a big red flag as we use Spring a lot. Could you update me if this is still existing issue as last comment was several years ago? 

Thanks,
Andrey

**Comment by dobrynya** [comment]
Hi Andrey @yerdn 
Don't know whether it is actual for you. Nevertheless I would like to notify you that I've released a new Nomin's version 1.2. I've fixed the issue you encountered when working with Tomcat.
You may be interested in upgrading Nomin and using its new method NominMapper.clearContext().
Best regards,
Dmitry
