### ISSUE TITLE
Mapping for classes without default constructors

### ISSUE THREAD

**Issue by amelnikoff** [dobrynya/nomin#18]
Hi there.
Don't know where to ask. On support maillist no one answered.

Is there any way to map classes without default constructors? Can't find any example for this case.

**Comment by dobrynya** [comment]
Hello Alexey

Sure. You can do the needed. You should use SunInstanceCreator. Please
introduce your own introspector and provide Nomin with the mentioned
instance creator. You may extend BaseReflectionIntrospector for instance.
Also you can use the Nomin's expression mechanism and create an instance of
your class in a closure as follows

a.withoutConstructorInstance = { new
WithoutDefaultConstructorClass(b.someProperty) }

What to choose is up to you. Hope it is helpful.

Best regards,
Dmitry

2016-04-28 10:37 GMT+03:00 Alexey Melnikov <notifications@github.com>:

**Comment by amelnikoff** [comment]
Hi Dmitriy.
Seems to me It wasn't clear what I want.

For example I have to pojos:

`class SimpleObject {
  String field;
  String anotherField;
  public SimpleObject(String field) {
    this.field = field;
  }
}

class SimpleObjectDTO {
  String field;
  String anotherField;
  public SimpleObjectDTO(String field) {
    this.field = field;
  }
}`

And I want to write mapping between them without using third pojo.

Something like that: 
`mappingFor a: SimpleObject, b: SimpleObjectDTO

automap()

a{b.field} = b{a.field}`

**Comment by dobrynya** [comment]
Hi Alexey

First of all, you should create an introspector instance with a
SunInstanceCreator as follows

Introspector introspector = new ReflectionIntrospector() {
  private InstanceCreator creator = new SunInstanceCreator(); // this
creator provides an ability to create an instance of a class without

              // default constructor, see implementation for the details
  public InstanceCreator instanceCreator() {
    return creator;
  }
}
// create a nomin instance and configure it
NominMapper nomin = new
Nomin().introspector(introspector).enableAutomapping();

// assuming SomeClass and WithoutDefaultConstructor have properties with
the same names.
WithoutDefaultConstructor wsc = nomin.map(new SomeClass(fieldValue),
WithoutDefaultConstructor.class);
assertEquals(fieldValue, wdc.getField());

Best regards,
Dmitry

2016-05-03 13:13 GMT+03:00 Alexey Melnikov <notifications@github.com>:

**Comment by amelnikoff** [comment]
Ah ok. Now I see it.
