### ISSUE TITLE
ContextMap

### ISSUE THREAD

**Issue by gustavorodrig** [dobrynya/nomin#19]
I am trying to create a contextMap and pass this to another mapping by ( mapper.map(ClassA, ClassB, new ContextMap(*\* HashMap() **).. but at the another mapping I cant retrive the object in the context that i passed.. 

How do I get the object by Key at the ContextMap?
I followed an example on Nomin wiki, just typing the key of the map, but I got an error ( propertyMissing )

Thanks in advance.

**Comment by dobrynya** [comment]
Hi man

Sorry for the delay :) 

Please look at my commit https://github.com/dobrynya/nomin/commit/83ac09659e5c3de65c5e9840da51ac9e5b5b7c39
There I've implemented a test using the context. Hope this will help you.
Best regards,
Dmitry
