### ISSUE TITLE
how to map to element to element mapping while using Map

### ISSUE THREAD

**Issue by SimplyAmuthan** [dobrynya/nomin#20]
Hi I am trying to map element to element wise in java.util.map
 basically the following is my source objects
`public class Message {`
    `private final Map<String, Object> data;`
`}`
and my destination object is just a `Map<String, Object>` So all I want is **not** to copy all the elements from the map  `Map<String, Object> data;` but selectively. So I came up with a mapping file something like as follows

`mappingFor a: Message, b: Map[String,java.lang.Object]`
`a.data["ID"] = b["ID"]`

but I am getting following exception
`Cannot cast object 'Map[String, Object]' with class 'org.nomin.util.TypeInfo' to class 'java.lang.Class' due to: java.lang.ClassNotFoundException: Map[String, Object]`

Could you please help me resolve this issue...?

**Comment by dobrynya** [comment]
Hi

Actually Nomin is not intended to map an object to the java.util.Map class. So I can advise to wrap your map instance withing some wrapper class as follows

```java
class MapWrapper {
  private Map<String, Object> properties;
}
```
The mapping can be something like that
```groovy
mappingFor a: Message, b: MapWrapper
a.data["ID"] = b.properties["ID"]
```
and so on

Hope this can help you

**Comment by SimplyAmuthan** [comment]
can't we make this just to work for Map... can we consider this as a new feature request...?

**Comment by dobrynya** [comment]
Maybe it is possible. I should think some time how it can be implemented

**Comment by dobrynya** [comment]
It is possible to use some parts from almost any JSON deserializer to populate a Map instance to Java class. Please search it in the Internet
