### ISSUE TITLE
String to date conversion is always lenient

### ISSUE THREAD

**Issue by ratoaq2** [dobrynya/nomin#22]
It's not possible to define string 2 date conversion without being lenient

```groovy
  void dateFormat(String pattern) {
    if (!entries) entry()
    SimpleDateFormat sdf = new SimpleDateFormat(pattern)
    def conversion = new String2DateConversion(sdf)
    convert to_a: conversion, to_b: conversion
  }
```

When I try to convert `2017-99-99` to date using pattern `yyyy-MM-dd` it will return a date `2025-06-07` but in my case I want an exception to be thrown.

There should be a way to define whether the date parser should be lenient or not:
```groovy
SimpleDateFormat sdf = new SimpleDateFormat(pattern)
sdf.setLenient(false)
```

**Comment by dobrynya** [comment]
Thanks for the report. Actually I've never heard of leniency of j.u.SimpleDateFormat :) Just don't know why they (sun guys) had implemented such a thing.

To avoid adding unneeded complexity to nomin mapping DSL is it more appropriate to set lenient = false by default in String2DateConversion?

**Comment by ratoaq2** [comment]
I also don't know why java has chosen to be lenient by default. Having it default to false makes much more sense, but I don't know if you're ok with that since it's a breaking change in String2DateConversion.

**Comment by dobrynya** [comment]
Yes, I will be a breaking change. I cannot do this by default. So as I said earlier my advice is to create your own conversion. Think it is not too inconvenient.
