### ISSUE TITLE
deep cloning/mapping

### ISSUE THREAD

**Issue by suryaaditya** [dobrynya/nomin#26]
Hi,
with autoMapping enabled and disablingCache. If the requirement is to map between same object types, how do we make sure the Obj hierarchy is deep cloned/mapped? i am observing the sub objects are not cloned but sharing the same reference. Appreciate help.

**Comment by dobrynya** [comment]
Hi @suryaaditya 
Could you create a test project with reproducing your issue? I will look to uderstand what is happening there.
Best regards,
Dmitry
