### ISSUE TITLE
Any way to have different introspectors for two sides?

### ISSUE THREAD

**Issue by zengxxcn** [dobrynya/nomin#27]
Hi,
Is there a way to specify different introspectors for side a and b? The context is I have the two different my data models so the ways to access properties are different, e.g. one is java bean with getters/setters whereas the other is XMLElement accessed by xpath. My workaround is combine them into one introspector which looks up in one way and if the first lookup is unlucky go the other way, but obviously it's not a perfect approach. So any chance I could define introspectors separately for side a and b respectively?

**Comment by dobrynya** [comment]
Hi @zengxxcn 

Unfortunately nomin has no such ability. But if you would like you can add it and make a pull request. I will merge your changes.

Best regards,
Dmitry

**Comment by ollio** [comment]
@zengxxcn it would be nice to have XML at one side and Pojos at the other.

**Comment by dobrynya** [comment]
@ollio I'm not sure whether nomin is suitable for XML parsing as there is a lot of libraries for such conversions. For example JAXB, XML beans and so on.
