### ISSUE TITLE
Date Conversions to custom Date type

### ISSUE THREAD

**Issue by tarioch** [dobrynya/nomin#32]
Is there a way to do an additional conversion after the String2Date conversion or is there another way to be able to use this syntax

```groovy
a.strDate = b.details.birth
dateFormat "dd-MM-yyyy"
```

to produce something except java.util.Date? E.g. java.time.LocalDateTime
I would like to do this somewhere globally so I don't have to provide custom code on each field that's mapped.

**Comment by dobrynya** [comment]
Hi
At this very moment there is no such an ability as nomin was made several years ago for JVM 1.7. But now we can add converters for the new date & time API. I need time to implement that. If you have some time you could do that and make a pull-request.

**Comment by tarioch** [comment]
What I'm struggling with is how to hook up the converters. Ideally I would like to do something like leave String2Date as is and then simply create ScalarConverters for converting to the custom types (e.g. java.time.LocalDateTime)

But as far as I can tell, the ScalarConverters are not called if String2Date conversion runs.

**Comment by ollio** [comment]
Hi, 

we solve it with a static conversion method:

```
a.geburtsdatum = b.geburtsdatum 
convert to_a: { MappingUtils.toDate(it) }
```
For a birthday a LocalDate should be sufficient, the time component is not necessary.

**Comment by tarioch** [comment]
We have already quite an amount of existing mappings and now are planning to change some of our classes from Date to LocalDate and would prefer not to having to adjust all the mappings.
Besides I think it would be nice to have this support also for others.

As we have a central point where all our mapping goes through, solving this with ScalarConverters would be very nice. That way Nomin can deliver the standard types like LocalDate, ... out of the box and it's easy to extend it for custom types (e.g. for older applications which still use Joda Time or even custom types.
Also as a nice side effect if we add some more ScalarConverters this will also extend the Java to Java conversions.

**Comment by tarioch** [comment]
Created PR #33  for the part to call the converters.

I did not yet add additional converters as currently the mvn source level is still at 1.7.
If it's ok to change this to 1.8, I'll create an additional PR afterwards for some standard converters.

**Comment by tarioch** [comment]
Hi @dobrynya any idea how to solve this in a way that can be merged in nomin?

**Comment by dobrynya** [comment]
Hi @tarioch 
Actually we need some configurable component that can convert a string into all of date & time related types. The most important thing is not to loose time zone if it's specified in the original data. So it needs to find a way to pass fields' types to perform conversion in String2DateConversion. Using Converters infrastructure is not appropriate for us as there must be a context -- date format description -- like yyyy-MM-dd etc. Yesterday I started to work on this feature. I suppose I can complete that until the next weekend.

**Comment by tarioch** [comment]
Sounds great. Might be worth it to make this component not even limited to Date/Time stuff. I could imagine other cases (e.g. special number formats) that could use the same infrastructure.
Kind of like a "parameterized" conversion.

**Comment by tarioch** [comment]
@dobrynya any chance you had any progress on this? At the moment we use a forked version with #33  applied, which is quite a pain, having a solution in upstream nomin would make things simpler. 
Is there anything I can do to help?
