### ISSUE TITLE
Problems with using closures in Groovy 2.5

### ISSUE THREAD

**Issue by nc-hlb** [dobrynya/nomin#38]
We have successfully used Nomin for quite some time in Groovy 2.4, but are running into trouble after an upgrade to Groovy 2.5. The core of the problem seems to be that closures work in a different context, so afterAtoB and Closure mapping rules have inconsistent understanding of what "a" and "b" is. We have items that correspond to JSON structures and want to map these onto models for our own usage, but data in the JSON is divided into various substructures. Our way to get around this is to map several items onto the same one. So we have ItemInfo and ItemData both being mapped onto our internal object CombinedItem. This is fine in Groovy 2.4, but after upgrading to 2.5, Closures in ItemData think that the variable "a" in the Closure is of the type ItemInfo and fail.

I have created a simple test setup that demonstrates this:
https://github.com/nc-hlb/nominmapper
If you run it in the Groovy 2.4 configuration all tests pass, but if you switch to using 2.5 they fail.

**Comment by dobrynya** [comment]
Hi @nc-hlb 
Is it possible for you to retain groovy 2.4? :)
Suppose there is a breaking change in groovy. I'm going to dive into this problem at this weekend. Unfortunately I have a lack of time. Sorry.

**Comment by nc-hlb** [comment]
We are going to have to switch at some point in the near future. I made a work-around, by passing instance into the closure call in ClosureRuleElem, then reading from that input instead of b/a in the closure mapping rules. I also moved all afterAtoB to the highest level objects. It seems to be working fine now, and if a fix to the closure context is made, I can just change all the closures and it should work and look as before.

**Comment by dobrynya** [comment]
Hi @nc-hlb 
It seems I've fixed the problem. Please upgrade your project to use nomin v1.2 and check whether the issue is gone. 
Also I've changed context management in a key aspect. It can have a positive effect for performance.
Please feel free to provide your feedback to the upgrade.
Thanks for using Nomin at your work.
Best regards,
Dmitry

**Comment by nc-hlb** [comment]
Yes, it has solved it. That is some quick work. Quick work!
